/*
 * easybimehlanding_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package EasyBimehLandingClient

import(
	"easybimehlanding_lib/configuration_pkg"
	"easybimehlanding_lib/filemanager_pkg"
	"easybimehlanding_lib/liabilitydoctorinsurance_pkg"
	"easybimehlanding_lib/carbody_pkg"
	"easybimehlanding_lib/electronicequipmentinsurance_pkg"
	"easybimehlanding_lib/otherinsurancetypes_pkg"
	"easybimehlanding_lib/thirdpartyinsurance_pkg"
	"easybimehlanding_lib/motorcycleinsurance_pkg"
	"easybimehlanding_lib/fireinsurance_pkg"
	"easybimehlanding_lib/earthquakeinsurance_pkg"
	"easybimehlanding_lib/travelinsurance_pkg"
	"easybimehlanding_lib/elevatorinsurance_pkg"
	"easybimehlanding_lib/main_pkg"
	"easybimehlanding_lib/combodata_pkg"
	"easybimehlanding_lib/trackingdamage_pkg"
	"easybimehlanding_lib/footer_pkg"
	"easybimehlanding_lib/insurancepolicyplan_pkg"
)


/*
 * Interface for the EASYBIMEHLANDING_IMPL
 */
type EASYBIMEHLANDING interface {
    FileManager()           filemanager_pkg.FILEMANAGER
    LiabilityDoctorInsurance()       liabilitydoctorinsurance_pkg.LIABILITYDOCTORINSURANCE
    CarBody()               carbody_pkg.CARBODY
    ElectronicEquipmentInsurance()       electronicequipmentinsurance_pkg.ELECTRONICEQUIPMENTINSURANCE
    OtherInsuranceTypes()       otherinsurancetypes_pkg.OTHERINSURANCETYPES
    ThirdPartyInsurance()       thirdpartyinsurance_pkg.THIRDPARTYINSURANCE
    MotorcycleInsurance()       motorcycleinsurance_pkg.MOTORCYCLEINSURANCE
    FireInsurance()         fireinsurance_pkg.FIREINSURANCE
    EarthquakeInsurance()       earthquakeinsurance_pkg.EARTHQUAKEINSURANCE
    TravelInsurance()       travelinsurance_pkg.TRAVELINSURANCE
    ElevatorInsurance()       elevatorinsurance_pkg.ELEVATORINSURANCE
    Main()                  main_pkg.MAIN
    ComboData()             combodata_pkg.COMBODATA
    TrackingDamage()        trackingdamage_pkg.TRACKINGDAMAGE
    Footer()                footer_pkg.FOOTER
    InsurancePolicyPlan()       insurancepolicyplan_pkg.INSURANCEPOLICYPLAN
    Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the EASYBIMEHLANDING interface returning EASYBIMEHLANDING_IMPL
 */
func NewEASYBIMEHLANDING() EASYBIMEHLANDING {
    easyBimehLandingClient := new(EASYBIMEHLANDING_IMPL)
    easyBimehLandingClient.config = configuration_pkg.NewCONFIGURATION()

    return easyBimehLandingClient
}
