/*
 * easybimehlanding_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package electronicequipmentinsurance_pkg

import "easybimehlanding_lib/configuration_pkg"
import "easybimehlanding_lib/models_pkg"

/*
 * Interface for the ELECTRONICEQUIPMENTINSURANCE_IMPL
 */
type ELECTRONICEQUIPMENTINSURANCE interface {
    GetElectronicEquipmentInsurance (string, string) (*models_pkg.BaseModelElectronicEquipmentInsurance, error)

    GetDeviceBrandTypes (int64, int64, string) (*models_pkg.BaseModelDeviceBrandTypes, error)

    GetDiviceFranchisee (int64, string) (*models_pkg.BaseModelDiviceFranchisee, error)
}

/*
 * Factory for the ELECTRONICEQUIPMENTINSURANCE interaface returning ELECTRONICEQUIPMENTINSURANCE_IMPL
 */
func NewELECTRONICEQUIPMENTINSURANCE(config configuration_pkg.CONFIGURATION) *ELECTRONICEQUIPMENTINSURANCE_IMPL {
    client := new(ELECTRONICEQUIPMENTINSURANCE_IMPL)
    client.config = config
    return client
}