/*
 * easybimehlanding_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package travelinsurance_pkg

import "easybimehlanding_lib/configuration_pkg"
import "easybimehlanding_lib/models_pkg"

/*
 * Interface for the TRAVELINSURANCE_IMPL
 */
type TRAVELINSURANCE interface {
    GetTravelInsurance (string, int64, string) (*models_pkg.BaseModelTravelInsurance, error)
}

/*
 * Factory for the TRAVELINSURANCE interaface returning TRAVELINSURANCE_IMPL
 */
func NewTRAVELINSURANCE(config configuration_pkg.CONFIGURATION) *TRAVELINSURANCE_IMPL {
    client := new(TRAVELINSURANCE_IMPL)
    client.config = config
    return client
}