/*
 * easybimehlanding_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package trackingdamage_pkg

import "easybimehlanding_lib/configuration_pkg"
import "easybimehlanding_lib/models_pkg"

/*
 * Interface for the TRACKINGDAMAGE_IMPL
 */
type TRACKINGDAMAGE interface {
    GetTrackingCode (string, string) (*models_pkg.BaseModelTrakingCode, error)

    CreateTrackingDamage (*models_pkg.TrackingDamageRequest, string, string) (*models_pkg.TrackingDamage, error)

    GetStatusStatusCollections (int64, string) (*models_pkg.BaseModelStatusStatusCollections, error)

    GetStatus (int64, string) (*models_pkg.BaseModelStatus, error)
}

/*
 * Factory for the TRACKINGDAMAGE interaface returning TRACKINGDAMAGE_IMPL
 */
func NewTRACKINGDAMAGE(config configuration_pkg.CONFIGURATION) *TRACKINGDAMAGE_IMPL {
    client := new(TRACKINGDAMAGE_IMPL)
    client.config = config
    return client
}