/*
 * easybimehlanding_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package otherinsurancetypes_pkg

import "easybimehlanding_lib/configuration_pkg"
import "easybimehlanding_lib/models_pkg"

/*
 * Interface for the OTHERINSURANCETYPES_IMPL
 */
type OTHERINSURANCETYPES interface {
    GetOtherInsuranceTypes (string, string) (*models_pkg.OtherInsuranceTypes, error)

    GetSendSmsToken (string, string, string) (*models_pkg.SendSmsToken, error)

    GetVerifySmsToken (string, int64, string, string, string, string) (*models_pkg.Status200, error)
}

/*
 * Factory for the OTHERINSURANCETYPES interaface returning OTHERINSURANCETYPES_IMPL
 */
func NewOTHERINSURANCETYPES(config configuration_pkg.CONFIGURATION) *OTHERINSURANCETYPES_IMPL {
    client := new(OTHERINSURANCETYPES_IMPL)
    client.config = config
    return client
}