/*
 * easybimehlanding_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package footer_pkg

import "easybimehlanding_lib/configuration_pkg"
import "easybimehlanding_lib/models_pkg"

/*
 * Interface for the FOOTER_IMPL
 */
type FOOTER interface {
    GetPortalLandingContactAbout (string) (*models_pkg.BaseModelPortalLandingContactAbout, error)

    GetFaqInsuranceCentre (string) (*models_pkg.BaseModelFaqInsuranceCentre, error)

    GetInsurancePolicyTracking (int64, int64, string) (*models_pkg.BaseModelInsurancePolicyTracking, error)
}

/*
 * Factory for the FOOTER interaface returning FOOTER_IMPL
 */
func NewFOOTER(config configuration_pkg.CONFIGURATION) *FOOTER_IMPL {
    client := new(FOOTER_IMPL)
    client.config = config
    return client
}