/*
 * easybimehlanding_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package combodata_pkg

import "easybimehlanding_lib/configuration_pkg"
import "easybimehlanding_lib/models_pkg"

/*
 * Interface for the COMBODATA_IMPL
 */
type COMBODATA interface {
    GetDamageType (string) (*models_pkg.BaseModelDamageType, error)

    GetInsuranceTypes (string, bool, string) (*models_pkg.InsuranceTypes, error)

    GetInsuranceCompanies (string, int64, string) (*models_pkg.InsuranceCompanies, error)
}

/*
 * Factory for the COMBODATA interaface returning COMBODATA_IMPL
 */
func NewCOMBODATA(config configuration_pkg.CONFIGURATION) *COMBODATA_IMPL {
    client := new(COMBODATA_IMPL)
    client.config = config
    return client
}