/*
 * easybimehlanding_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package motorcycleinsurance_pkg

import "easybimehlanding_lib/configuration_pkg"
import "easybimehlanding_lib/models_pkg"

/*
 * Interface for the MOTORCYCLEINSURANCE_IMPL
 */
type MOTORCYCLEINSURANCE interface {
    GetCarBrands (int64, string) (*models_pkg.CarBrands, error)

    GetCarBrandTips (int64, string) (*models_pkg.CarBrandTips, error)

    GetHasPlan (string, int64, string) (*models_pkg.HasPlan, error)
}

/*
 * Factory for the MOTORCYCLEINSURANCE interaface returning MOTORCYCLEINSURANCE_IMPL
 */
func NewMOTORCYCLEINSURANCE(config configuration_pkg.CONFIGURATION) *MOTORCYCLEINSURANCE_IMPL {
    client := new(MOTORCYCLEINSURANCE_IMPL)
    client.config = config
    return client
}