/*
 * easybimehlanding_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package carbody_pkg

import "easybimehlanding_lib/configuration_pkg"
import "easybimehlanding_lib/models_pkg"

/*
 * Interface for the CARBODY_IMPL
 */
type CARBODY interface {
    GetCarBrand (string) (*models_pkg.CarBrand, error)

    GetCarBrandTips (int64, string) (*models_pkg.CarBrandTips, error)

    GetHasPlan (string, int64, string) (*models_pkg.HasPlan, error)
}

/*
 * Factory for the CARBODY interaface returning CARBODY_IMPL
 */
func NewCARBODY(config configuration_pkg.CONFIGURATION) *CARBODY_IMPL {
    client := new(CARBODY_IMPL)
    client.config = config
    return client
}