/*
 * easybimehlanding_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package earthquakeinsurance_pkg

import "easybimehlanding_lib/configuration_pkg"
import "easybimehlanding_lib/models_pkg"

/*
 * Interface for the EARTHQUAKEINSURANCE_IMPL
 */
type EARTHQUAKEINSURANCE interface {
    GetEarthquake (string, int64, int64, string) (*models_pkg.BaseModelEarthquake, error)
}

/*
 * Factory for the EARTHQUAKEINSURANCE interaface returning EARTHQUAKEINSURANCE_IMPL
 */
func NewEARTHQUAKEINSURANCE(config configuration_pkg.CONFIGURATION) *EARTHQUAKEINSURANCE_IMPL {
    client := new(EARTHQUAKEINSURANCE_IMPL)
    client.config = config
    return client
}