/*
 * easybimehlanding_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package insurancepolicyplan_pkg

import "easybimehlanding_lib/configuration_pkg"
import "easybimehlanding_lib/models_pkg"

/*
 * Interface for the INSURANCEPOLICYPLAN_IMPL
 */
type INSURANCEPOLICYPLAN interface {
    GetSpecialPlan (string, string) (*models_pkg.BaseModelSpecialPlan, error)
}

/*
 * Factory for the INSURANCEPOLICYPLAN interaface returning INSURANCEPOLICYPLAN_IMPL
 */
func NewINSURANCEPOLICYPLAN(config configuration_pkg.CONFIGURATION) *INSURANCEPOLICYPLAN_IMPL {
    client := new(INSURANCEPOLICYPLAN_IMPL)
    client.config = config
    return client
}